# Estadistica aplicada

## Jorge Sebastian Aguirre Jimenez 1947870 G41

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
from lifelines import CoxPHFitter
import seaborn as sns

In [9]:
from lifelines import ExponentialFitter
from lifelines import WeibullFitter
from lifelines import LogNormalFitter
from lifelines import LogNormalAFTFitter

In [10]:
renunciar=pd.read_csv('https://raw.githubusercontent.com/jimmyzac/Estadistica-Aplicada-FCFM-UANL/main/bases_datos/desercion_laboral.csv')

In [11]:
renunciar

,satisfaccion,evaluacion,proyectos,promedio_horas_mes,semestre,accidente,renunciar,ascenso_5years,departamento,salario
0,3.8,5.3,2,157,3,0,1,0,ventas,bajo
1,8.0,8.6,5,262,6,0,1,0,ventas,medio
2,1.1,8.8,7,272,4,0,1,0,ventas,medio
3,7.2,8.7,5,223,5,0,1,0,ventas,bajo
4,3.7,5.2,2,159,3,0,1,0,ventas,bajo
...,...,...,...,...,...,...,...,...,...,...
14994,4.0,5.7,2,151,3,0,1,0,soporte,bajo
14995,3.7,4.8,2,160,3,0,1,0,soporte,bajo
14996,3.7,5.3,2,143,3,0,1,0,soporte,bajo
14997,1.1,9.6,6,280,4,0,1,0,soporte,bajo
14998,3.7,5.2,2,158,3,0,1,0,soporte,bajo

In [12]:
renunciar.isnull().sum()

satisfaccion           0
evaluacion             0
proyectos              0
promedio_horas_mes     0
semestre               0
accidente              0
renunciar              0
ascenso_5years         0
departamento          26
salario                0
dtype: int64

In [13]:
renunciar=renunciar.dropna()

In [14]:
renunciar.duplicated().sum()

2982

In [15]:
renunciar=renunciar.drop_duplicates(keep='first').reset_index(drop=True)

In [16]:
renunciar.dtypes

satisfaccion          float64
evaluacion            float64
proyectos               int64
promedio_horas_mes      int64
semestre                int64
accidente               int64
renunciar               int64
ascenso_5years          int64
departamento           object
salario                object
dtype: object

In [17]:
renunciar['satisfaccion']=renunciar['satisfaccion'].astype('int64')
renunciar['evaluacion']=renunciar['evaluacion'].astype('int64')

In [18]:
dummies1 = pd.get_dummies(renunciar['departamento'], prefix='departamento').astype(int)
dummies2 = pd.get_dummies(renunciar['salario'], prefix='salario').astype(int)

In [19]:
dummies2

       salario_alto  salario_bajo  salario_medio
0                 0             1              0
1                 0             0              1
2                 0             0              1
3                 0             1              0
4                 0             1              0
...             ...           ...            ...
11986             0             1              0
11987             0             1              0
11988             0             1              0
11989             0             1              0
11990             0             1              0

[11991 rows x 3 columns]

In [20]:
dummies1=dummies1[['departamento_administraciÃ³n','departamento_contabilidad','departamento_desarrollo de producto','departamento_informÃ¡tica','departamento_mantenimiento','departamento_mercadotecnia','departamento_recursos humanos','departamento_soporte','departamento_ventas']]
dummies2=dummies2[['salario_bajo','salario_medio']]

In [21]:
renunciar=pd.concat([renunciar,dummies1,dummies2],axis=1)

In [22]:
renunciar=renunciar.drop('departamento',axis=1)
renunciar=renunciar.drop('salario',axis=1)

In [23]:
renunciar.dtypes

satisfaccion                           int64
evaluacion                             int64
proyectos                              int64
promedio_horas_mes                     int64
semestre                               int64
accidente                              int64
renunciar                              int64
ascenso_5years                         int64
departamento_administraciÃ³n            int32
departamento_contabilidad              int32
departamento_desarrollo de producto    int32
departamento_informÃ¡tica               int32
departamento_mantenimiento             int32
departamento_mercadotecnia             int32
departamento_recursos humanos          int32
departamento_soporte                   int32
departamento_ventas                    int32
salario_bajo                           int32
salario_medio                          int32
dtype: object

In [24]:
renunciar.isnull().sum()

satisfaccion                           0
evaluacion                             0
proyectos                              0
promedio_horas_mes                     0
semestre                               0
accidente                              0
renunciar                              0
ascenso_5years                         0
departamento_administraciÃ³n            0
departamento_contabilidad              0
departamento_desarrollo de producto    0
departamento_informÃ¡tica               0
departamento_mantenimiento             0
departamento_mercadotecnia             0
departamento_recursos humanos          0
departamento_soporte                   0
departamento_ventas                    0
salario_bajo                           0
salario_medio                          0
dtype: int64

In [25]:
renunciar.describe()

,satisfaccion,evaluacion,proyectos,promedio_horas_mes,semestre,accidente,renunciar,ascenso_5years,departamento_administraciÃ³n,departamento_contabilidad,departamento_desarrollo de producto,departamento_informÃ¡tica,departamento_mantenimiento,departamento_mercadotecnia,departamento_recursos humanos,departamento_soporte,departamento_ventas,salario_bajo,salario_medio
count,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.00000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000,11991.000000
mean,5.851889,6.707948,3.802852,200.473522,3.364857,0.154282,0.166041,0.016929,0.036361,0.051789,0.057210,0.081394,0.18714,0.056125,0.050121,0.151864,0.270119,0.478692,0.438746
std,2.397506,1.703189,1.163238,48.727813,1.330240,0.361234,0.372133,0.129012,0.187194,0.221610,0.232252,0.273451,0.39004,0.230173,0.218204,0.358904,0.444040,0.499567,0.496254
min,0.000000,3.000000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,5.000000,3.000000,157.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6.000000,7.000000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,8.000000,8.000000,5.000000,243.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
max,10.000000,10.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [26]:
cph1 = CoxPHFitter().fit(renunciar, 'semestre', 'renunciar')
cph1.print_summary()
cph1.params_
cph1.hazard_ratios_

ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

<lifelines.CoxPHFitter: fitted with 11991 total observations, 10000 right-censored observations>
             duration col = 'semestre'
                event col = 'renunciar'
      baseline estimation = breslow
   number of observations = 11991
number of events observed = 1991
   partial log-likelihood = -15905.76
         time fit was run = 2023-09-26 18:54:18 UTC

---
                                      coef  exp(coef)   se(coef)   coef lower 95%   coef upper 95%  exp(coef) lower 95%  exp(coef) upper 95%
covariate
satisfaccion                         -0.24       0.79       0.01            -0.25            -0.22                 0.78                 0.80
evaluacion                           -0.01       0.99       0.01            -0.04             0.01                 0.96                 1.01
proyectos                            -0.28       0.75       0.02            -0.32            -0.24                 0.73                 0.78
promedio_horas_mes                    0.00       1.00       0.00             0.00             0.00                 1.00                 1.00
accidente                            -1.24       0.29       0.10            -1.44            -1.05                 0.24                 0.35
ascenso_5years                       -1.37       0.25       0.36            -2.07            -0.67                 0.13                 0.51
departamento_administraciÃ³n           0.23       1.25       0.18            -0.12             0.57                 0.89                 1.77
departamento_contabilidad             0.26       1.30       0.14            -0.02             0.54                 0.98                 1.72
departamento_desarrollo de producto   0.35       1.42       0.14             0.07             0.64                 1.07                 1.89
departamento_informÃ¡tica              0.30       1.35       0.13             0.04             0.56                 1.04                 1.76
departamento_mantenimiento            0.44       1.55       0.12             0.20             0.67                 1.23                 1.96
departamento_mercadotecnia            0.35       1.41       0.14             0.06             0.63                 1.07                 1.87
departamento_recursos humanos         0.45       1.57       0.14             0.17             0.73                 1.18                 2.08
departamento_soporte                  0.46       1.58       0.12             0.22             0.70                 1.24                 2.01
departamento_ventas                   0.36       1.43       0.12             0.13             0.59                 1.14                 1.80
salario_bajo                          1.54       4.65       0.15             1.25             1.83                 3.48                 6.22
salario_medio                         1.15       3.15       0.15             0.85             1.44                 2.35                 4.22

                                      cmp to      z      p   -log2(p)
covariate
satisfaccion                            0.00 -26.22 <0.005     500.95
evaluacion                              0.00  -0.97   0.33       1.60
proyectos                               0.00 -14.30 <0.005     151.75
promedio_horas_mes                      0.00   4.10 <0.005      14.55
accidente                               0.00 -12.39 <0.005     114.67
ascenso_5years                          0.00  -3.85 <0.005      13.08
departamento_administraciÃ³n             0.00   1.27   0.20       2.30
departamento_contabilidad               0.00   1.79   0.07       3.78
departamento_desarrollo de producto     0.00   2.43   0.01       6.06
departamento_informÃ¡tica                0.00   2.23   0.03       5.28
departamento_mantenimiento              0.00   3.67 <0.005      11.98
departamento_mercadotecnia              0.00   2.40   0.02       5.93
departamento_recursos humanos           0.00   3.14 <0.005       9.19
departamento_soporte                    0.00   3.73 <0.005      12.37
departamento_ventas                     0.00   3.07 <0.005       8.87
salario_bajo                            0.00  10.35 <0.005      80.94
salario_medio                           0.00   7.66 <0.005      45.59
---
Concordance = 0.84
Partial AIC = 31845.52
log-likelihood ratio test = 1317.54 on 17 df
-log2(p) of ll-ratio test = 893.93

covariate
satisfaccion                           0.790519
evaluacion                             0.986689
proyectos                              0.754029
promedio_horas_mes                     1.001942
accidente                              0.288047
ascenso_5years                         0.253654
departamento_administraciÃ³n            1.252816
departamento_contabilidad              1.296533
departamento_desarrollo de producto    1.421475
departamento_informÃ¡tica               1.350408
departamento_mantenimiento             1.551543
departamento_mercadotecnia             1.412807
departamento_recursos humanos          1.569056
departamento_soporte                   1.580005
departamento_ventas                    1.430542
salario_bajo                           4.652306
salario_medio                          3.147593
Name: exp(coef), dtype: float64

**SatisfacciÃ³n**, Se rechaza H0, lo que indica que si un empleado esta satisfecho entonces reduce en un 21% el riesgo de que renuncie de la empresa.

**EvaluaciÃ³n**, No se rechaza H0, la evaluaciÃ³n no afecta el riesgo de que un empleado renuncie.

**Proyectos**, Se rechaza H0, el nÃºmero de proyectos reduce en un 25% el riesgo de que un empleado renuncie.

**Promedio_horas_mes**, Se rechaza H0, el nÃºmero de horas trabajadas aumenta en un 0.19% el riesgo de que un empleado renuncie.

**Accidentes**, se rechaza H0, si hubo accidentes se reduce en un 71% el riesgo de que un empleado renuncie con respecto con los que no tuvieron un accidente.

**Ascenso_5years**, Se rechaza H0, si un empleado tiene un ascenso se reduce en un 75% el riesgo de que renuncie con respecto a los que no tuvieron un ascenso.

**Departamento de administraciÃ³n**, No se rechaza Ho, lo que indica que trabajar en el departamento de administraciÃ³n no afecta al riesgo de renuncia con respecto a sÃ­ trabajar en el departamento de investigaciÃ³n.

**Departamento de contabilidad**, No se rechaza Ho, lo que indica que trabajar en el departamento de contabilidad no afecta al riesgo de renuncia con respecto a sÃ­ trabajar en el departamento de investigaciÃ³n.

**Departamento de desarrollo de productos**, Se rechaza Ho, trabajar en el departamento de desarrollo de productos incrementa en un 42% el riesgo de renunciar con respecto a trabajar en el departamento de investigaciÃ³n.

**Departamento de informÃ¡tica**, Se rechaza Ho, trabajar en el departamento de informÃ¡tica incrementa en un 35% el riesgo de renunciar con respecto a trabajar en el departamento de investigaciÃ³n.

**Departamento de mantenimiento**, Se rechaza Ho, trabajar en el departamento de mantenimiento incrementa en un 55% el riesgo de renunciar con respecto a trabajar en el departamento de investigaciÃ³n.

**Departamento de mercadotecnia**, Se rechaza Ho, trabajar en el departamento de mercadotecnia incrementa en un 41% el riesgo de renunciar con respecto a trabajar en el departamento de investigaciÃ³n.

**Departamento de recursos humanos**, Se rechaza Ho, trabajar en el departamento de recursos humanos incrementa en un 57% el riesgo de renunciar con respecto a trabajar en el departamento de investigaciÃ³n.

**Departamento de soporte**, Se rechaza Ho, trabajar en el departamento de soporte incrementa en un 58% el riesgo de renunciar con respecto a trabajar en el departamento de investigaciÃ³n.

**Departamento de ventas**, Se rechaza Ho, trabajar en el departamento de ventas incrementa en un 43% el riesgo de renunciar con respecto a trabajar en el departamento de investigaciÃ³n.

**Salario bajo**, Se rechaza H0, recibir un salario bajo incrementa en un 365% el riesgo de que un empleado renuncie con respecto a los que ganan un salario alto.

**Salario medio**, Se rechaza H0, recibir un salario medio incrementa el riesgo de que un empleado renuncie en un 215% con respecto a los que ganan un salario alto.

Lo que puede hacer la empresa para disminuir las renuncias es mantener a los empelados satisfechos, asignarles una cantidad prudente de proyectos, no ponerlos a trabajar un largo horario y darles ascenso en un perido no mayor de 5 aÃ±os.

In [33]:
cph1.check_assumptions(renunciar, p_value_threshold=0.05)

The ``p_value_threshold`` is set at 0.05. Even under the null hypothesis of no violations, some
covariates will be below the threshold by chance. This is compounded when there are many covariates.
Similarly, when there are lots of observations, even minor deviances from the proportional hazard
assumption will be flagged.

With that in mind, it's best to use a combination of statistical tests and visual tests to determine
the most serious violations. Produce visual plots using ``check_assumptions(..., show_plots=True)``
and looking for non-constant lines. See link [A] below for a full example.

ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

<lifelines.StatisticalResult: proportional_hazard_test>
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 11991 total observations, 10000 right-censored observations>
         test_name = proportional_hazard_test

---
                                          test_statistic      p  -log2(p)
accidente                           km              0.06   0.80      0.32
                                    rank            1.33   0.25      2.00
ascenso_5years                      km              3.93   0.05      4.40
                                    rank            7.11   0.01      7.03
departamento_administraciÃ³n         km              5.13   0.02      5.41
                                    rank            5.76   0.02      5.93
departamento_contabilidad           km              0.23   0.63      0.66
                                    rank            1.51   0.22      2.19
departamento_desarrollo de producto km              0.83   0.36      1.46
                                    rank            0.72   0.39      1.34
departamento_informÃ¡tica            km              0.61   0.43      1.21
                                    rank            0.67   0.41      1.28
departamento_mantenimiento          km              0.60   0.44      1.19
                                    rank            2.50   0.11      3.14
departamento_mercadotecnia          km              2.64   0.10      3.26
                                    rank            6.26   0.01      6.34
departamento_recursos humanos       km              0.96   0.33      1.61
                                    rank            3.36   0.07      3.90
departamento_soporte                km              0.01   0.92      0.12
                                    rank            1.01   0.32      1.66
departamento_ventas                 km              1.28   0.26      1.96
                                    rank            4.82   0.03      5.15
evaluacion                          km            456.70 <0.005    334.19
                                    rank          433.86 <0.005    317.68
promedio_horas_mes                  km            262.79 <0.005    193.91
                                    rank          303.15 <0.005    223.13
proyectos                           km            564.24 <0.005    411.91
                                    rank          685.75 <0.005    499.70
salario_bajo                        km              0.36   0.55      0.87
                                    rank            0.00   0.96      0.06
salario_medio                       km              0.15   0.69      0.53
                                    rank            0.10   0.75      0.42
satisfaccion                        km           1217.52 <0.005    883.70
                                    rank          825.64 <0.005    600.75

1. Variable 'satisfaccion' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'satisfaccion' might be incorrect. That is, there
may be non-linear terms missing. The proportional hazard test used is very sensitive to incorrect
functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'satisfaccion' using pd.cut, and then specify it in
`strata=['satisfaccion', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


2. Variable 'evaluacion' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'evaluacion' might be incorrect. That is, there may
be non-linear terms missing. The proportional hazard test used is very sensitive to incorrect
functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'evaluacion' using pd.cut, and then specify it in
`strata=['evaluacion', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


3. Variable 'proyectos' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 6), you can include `strata=['proyectos', ...]` in the
call in `.fit`. See documentation in link [E] below.

4. Variable 'promedio_horas_mes' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'promedio_horas_mes' might be incorrect. That is,
there may be non-linear terms missing. The proportional hazard test used is very sensitive to
incorrect functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'promedio_horas_mes' using pd.cut, and then specify it in
`strata=['promedio_horas_mes', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


5. Variable 'ascenso_5years' failed the non-proportional test: p-value is 0.0077.

   Advice: with so few unique values (only 2), you can include `strata=['ascenso_5years', ...]` in
the call in `.fit`. See documentation in link [E] below.

6. Variable 'departamento_administraciÃ³n' failed the non-proportional test: p-value is 0.0164.

   Advice: with so few unique values (only 2), you can include
`strata=['departamento_administraciÃ³n', ...]` in the call in `.fit`. See documentation in link [E]
below.

7. Variable 'departamento_mercadotecnia' failed the non-proportional test: p-value is 0.0123.

   Advice: with so few unique values (only 2), you can include
`strata=['departamento_mercadotecnia', ...]` in the call in `.fit`. See documentation in link [E]
below.

8. Variable 'departamento_ventas' failed the non-proportional test: p-value is 0.0281.

   Advice: with so few unique values (only 2), you can include `strata=['departamento_ventas', ...]`
in the call in `.fit`. See documentation in link [E] below.

---
[A]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html
[B]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Bin-variable-and-stratify-on-it
[C]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Introduce-time-varying-covariates
[D]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Modify-the-functional-form
[E]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Stratification

[]

el supuesto de riesgo propocrional no se cumple

In [30]:
exponencial = ExponentialFitter().fit(renunciar['semestre'],renunciar['renunciar'])
weibull = WeibullFitter().fit(renunciar['semestre'],renunciar['renunciar'])
lognormal = LogNormalFitter().fit(renunciar['semestre'],renunciar['renunciar'])

In [31]:
exponencial.AIC_, weibull.AIC_, lognormal.AIC_

(15965.45892201228, 12511.512867661068, 11587.92169210356)

In [32]:
LogNormalAFT = LogNormalAFTFitter().fit(renunciar,'semestre','renunciar')
LogNormalAFT.print_summary()

ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

<lifelines.LogNormalAFTFitter: fitted with 11991 total observations, 10000 right-censored observations>
             duration col = 'semestre'
                event col = 'renunciar'
   number of observations = 11991
number of events observed = 1991
           log-likelihood = -4899.95
         time fit was run = 2023-09-26 18:55:59 UTC

---
                                             coef  exp(coef)   se(coef)   coef lower 95%   coef upper 95%  exp(coef) lower 95%  exp(coef) upper 95%
param  covariate
mu_    accidente                             0.26       1.30       0.02             0.22             0.30                 1.25                 1.35
       ascenso_5years                        0.36       1.44       0.06             0.24             0.49                 1.27                 1.63
       departamento_administraciÃ³n           0.05       1.05       0.04            -0.03             0.13                 0.97                 1.14
       departamento_contabilidad            -0.05       0.96       0.03            -0.11             0.02                 0.89                 1.02
       departamento_desarrollo de producto  -0.05       0.95       0.03            -0.12             0.02                 0.89                 1.02
       departamento_informÃ¡tica             -0.05       0.95       0.03            -0.11             0.01                 0.90                 1.01
       departamento_mantenimiento           -0.08       0.92       0.03            -0.13            -0.02                 0.88                 0.98
       departamento_mercadotecnia           -0.04       0.96       0.03            -0.10             0.03                 0.90                 1.03
       departamento_recursos humanos        -0.09       0.92       0.03            -0.16            -0.02                 0.86                 0.98
       departamento_soporte                 -0.08       0.92       0.03            -0.14            -0.03                 0.87                 0.97
       departamento_ventas                  -0.06       0.94       0.03            -0.11            -0.00                 0.90                 1.00
       evaluacion                            0.01       1.01       0.00            -0.00             0.01                 1.00                 1.01
       promedio_horas_mes                   -0.00       1.00       0.00            -0.00            -0.00                 1.00                 1.00
       proyectos                             0.09       1.10       0.01             0.08             0.10                 1.09                 1.11
       salario_bajo                         -0.37       0.69       0.03            -0.43            -0.31                 0.65                 0.73
       salario_medio                        -0.29       0.75       0.03            -0.35            -0.23                 0.71                 0.80
       satisfaccion                          0.07       1.07       0.00             0.06             0.07                 1.06                 1.07
       Intercept                             1.39       4.01       0.04             1.30             1.48                 3.68                 4.38
sigma_ Intercept                            -1.11       0.33       0.02            -1.14            -1.08                 0.32                 0.34

                                             cmp to      z      p   -log2(p)
param  covariate
mu_    accidente                               0.00  12.95 <0.005     124.97
       ascenso_5years                          0.00   5.74 <0.005      26.69
       departamento_administraciÃ³n             0.00   1.26   0.21       2.26
       departamento_contabilidad               0.00  -1.34   0.18       2.48
       departamento_desarrollo de producto     0.00  -1.46   0.14       2.80
       departamento_informÃ¡tica                0.00  -1.51   0.13       2.92
       departamento_mantenimiento              0.00  -2.81 <0.005       7.65
       departamento_mercadotecnia              0.00  -1.07   0.28       1.81
       departamento_recursos humanos           0.00  -2.60   0.01       6.73
       departamento_soporte                    0.00  -2.90 <0.005       8.06
       departamento_ventas                     0.00  -2.13   0.03       4.92
       evaluacion                              0.00   1.73   0.08       3.57
       promedio_horas_mes                      0.00  -2.52   0.01       6.41
       proyectos                               0.00  18.08 <0.005     240.41
       salario_bajo                            0.00 -12.49 <0.005     116.51
       salario_medio                           0.00  -9.58 <0.005      69.76
       satisfaccion                            0.00  28.37 <0.005     585.91
       Intercept                               0.00  31.19 <0.005     707.22
sigma_ Intercept                               0.00 -73.11 <0.005        inf
---
Concordance = 0.85
AIC = 9837.90
log-likelihood ratio test = 1784.02 on 17 df
-log2(p) of ll-ratio test = inf